// Community events gathered from each group's own website or ticket page, so the calendar
// isn't empty before groups start submitting their own. Every entry links to where it came
// from and shows the date it was checked.
//
// Temporary: once the Notion backend is connected, run importStarterListings() in the
// backend and these become real Community Events rows.
window.SING_COMMUNITY_SEED = [
 {
  "id": "seed-edmetro-chorus-rehearsal-new-members-2026-09-14",
  "title": "EdMetro Chorus rehearsal - new members welcome",
  "group": "Edmonton Metropolitan Chorus",
  "type": "Open rehearsal",
  "date": "2026-09-14",
  "verified": "2026-09-12",
  "sourceName": "edmetrochorus.ca",
  "time": "19:00",
  "endTime": "21:00",
  "venue": "Strathearn United Church",
  "address": "8510 95 Ave NW, Edmonton, AB",
  "description": "Season-opening rehearsal that newcomers may join; no audition is required, though some choral or vocal experience is expected.",
  "link": "https://edmetrochorus.ca/how-to-join/",
  "source": "https://edmetrochorus.ca/wp-content/uploads/2026/09/EdMetro-Chorus-REH-PERF-Schedule-2026-2027-v2.pdf"
 },
 {
  "id": "seed-evm-open-rehearsal-2026-09-14",
  "title": "EVM open rehearsal",
  "group": "Edmonton Vocal Minority",
  "type": "Open rehearsal",
  "date": "2026-09-14",
  "verified": "2026-09-12",
  "sourceName": "evmchoir.com",
  "time": "19:00",
  "endTime": "21:00",
  "venue": "Unitarian Church of Edmonton",
  "address": "10804 119 Street NW, Edmonton, AB",
  "description": "Edmonton's queer community choir opens a rehearsal to anyone curious about joining; no audition and no prior training required.",
  "link": "https://evmchoir.com/join",
  "source": "https://evmchoir.com/join"
 },
 {
  "id": "seed-vocal-alchemy-open-rehearsal-2026-09-15",
  "title": "Vocal Alchemy open rehearsal",
  "group": "Vocal Alchemy",
  "type": "Open rehearsal",
  "date": "2026-09-15",
  "verified": "2026-09-12",
  "sourceName": "vocalalchemy.com",
  "time": "19:00",
  "endTime": "21:30",
  "venue": "Central Edmonton rehearsal hall (address given on request)",
  "description": "Prospective singers can sit in on a Tuesday rehearsal of this community choir before deciding whether to join for the year.",
  "link": "https://www.vocalalchemy.com/sing-with-us",
  "source": "https://www.vocalalchemy.com/sing-with-us"
 },
 {
  "id": "seed-sing-with-ekosingers-open-rehearsal-2026-09-15",
  "title": "Sing with EKOSingers! Open Rehearsal",
  "group": "EKOSingers",
  "type": "Open rehearsal",
  "date": "2026-09-15",
  "verified": "2026-09-12",
  "sourceName": "tockify.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "St. Luke's Anglican Church",
  "address": "8424 95 Avenue NW, Edmonton, AB",
  "description": "Curious singers can sit in on a regular rehearsal of this pop and jazz choir; altos, tenors and basses are especially wanted.",
  "price": "Free",
  "link": "https://www.ekosingers.com/joinus",
  "source": "https://tockify.com/choiralberta/detail/1407/1788917400000"
 },
 {
  "id": "seed-camp-he-ho-ha-coaching-weekend-2026-09-18",
  "title": "Camp He Ho Ha Coaching Weekend",
  "group": "Edmonton Barbershop Harmony Chorus",
  "type": "Workshop or class",
  "date": "2026-09-18",
  "verified": "2026-09-12",
  "sourceName": "ebhchorus.ca",
  "endDate": "2026-09-20",
  "venue": "Camp He Ho Ha",
  "description": "A residential barbershop retreat where the chorus works on singing and stagecraft with coaches Steve Scott and Marty Lovick.",
  "link": "https://ebhchorus.ca/event/camp-he-ho-ha-coaching-weekend/",
  "source": "https://ebhchorus.ca/events/"
 },
 {
  "id": "seed-a-cabaret-spirit-of-broadway-2026-09-18",
  "title": "A Cabaret - Spirit of Broadway",
  "group": "Spirit of Hope United Church",
  "type": "Concert",
  "date": "2026-09-18",
  "verified": "2026-09-12",
  "sourceName": "edmontonarts.ca",
  "time": "19:00",
  "venue": "Spirit of Hope United Church",
  "address": "7909 82 Avenue NW, Edmonton, AB",
  "description": "Young Edmonton musical-theatre singers, several straight out of the Fringe, perform an evening of songs pulled from a range of Broadway shows.",
  "price": "$15",
  "link": "https://www.edmontonarts.ca/event/a-cabaret-spirit-of-broadway",
  "source": "https://www.edmontonarts.ca/event-category/music"
 },
 {
  "id": "seed-fairytale-dreams-2026-09-19",
  "title": "Fairytale Dreams",
  "group": "Pro Coro Canada",
  "type": "Concert",
  "date": "2026-09-19",
  "verified": "2026-09-12",
  "sourceName": "tickettailor.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "McDougall United Church",
  "address": "10086 MacDonald Drive NW, Edmonton, AB",
  "description": "Pro Coro opens its 26.27 season with folk tales and legends, joined by recorder player Matthias Maute and regional high school singers.",
  "price": "$38 general, $10 student (plus tax)",
  "link": "https://www.tickettailor.com/events/procorocanada/2318111",
  "source": "https://www.tickettailor.com/events/procorocanada/"
 },
 {
  "id": "seed-improve-your-singing-voice-workshop-2026-09-20",
  "title": "Improve Your Singing Voice - Workshop",
  "group": "Alberta Northern Lights Chorus",
  "type": "Workshop or class",
  "date": "2026-09-20",
  "verified": "2026-09-12",
  "sourceName": "eventbrite.ca",
  "time": "13:00",
  "endTime": "15:00",
  "venue": "Freemasons Hall",
  "address": "10318 100 Avenue NW, Edmonton, AB",
  "description": "A relaxed afternoon for women and treble voices working on vocal confidence, freedom and consistency, with refreshments afterwards.",
  "price": "Free",
  "link": "https://www.albertanorthernlightschorus.com/improve-your-singing-voice",
  "source": "https://www.eventbrite.ca/e/improve-your-singing-voice-workshop-tickets-1998698813956"
 },
 {
  "id": "seed-u-of-a-days-music-concert-2026-09-20",
  "title": "U of A Days Music Concert",
  "group": "University of Alberta Madrigal Singers and Concert Choir",
  "type": "Concert",
  "date": "2026-09-20",
  "verified": "2026-09-12",
  "sourceName": "ualberta.ca",
  "time": "14:00",
  "endTime": "15:30",
  "venue": "Horowitz Events Centre, Students' Union Building, University of Alberta",
  "description": "Two university choirs share an afternoon bill with the wind ensemble and symphony orchestra as part of the campus open-house weekend.",
  "price": "$5 in person; free online livestream",
  "link": "https://www.ualberta.ca/en/music/concert-listings/index.html",
  "source": "https://www.ualberta.ca/en/music/concert-listings/index.html"
 },
 {
  "id": "seed-edmetro-chorus-rehearsal-new-members-2026-09-21",
  "title": "EdMetro Chorus rehearsal - new members welcome",
  "group": "Edmonton Metropolitan Chorus",
  "type": "Open rehearsal",
  "date": "2026-09-21",
  "verified": "2026-09-12",
  "sourceName": "edmetrochorus.ca",
  "time": "19:00",
  "endTime": "21:00",
  "venue": "Strathearn United Church",
  "address": "8510 95 Ave NW, Edmonton, AB",
  "description": "Second chance of the fall for prospective singers to sit in on a rehearsal of this non-auditioned SATB community chorus.",
  "link": "https://edmetrochorus.ca/how-to-join/",
  "source": "https://edmetrochorus.ca/wp-content/uploads/2026/09/EdMetro-Chorus-REH-PERF-Schedule-2026-2027-v2.pdf"
 },
 {
  "id": "seed-evm-open-rehearsal-2026-09-21",
  "title": "EVM open rehearsal",
  "group": "Edmonton Vocal Minority",
  "type": "Open rehearsal",
  "date": "2026-09-21",
  "verified": "2026-09-12",
  "sourceName": "evmchoir.com",
  "time": "19:00",
  "endTime": "21:00",
  "venue": "Unitarian Church of Edmonton",
  "address": "10804 119 Street NW, Edmonton, AB",
  "description": "Second of three drop-in rehearsals where prospective singers can try out the non-auditioned LGBTQ+ choir before committing.",
  "link": "https://evmchoir.com/join",
  "source": "https://evmchoir.com/join"
 },
 {
  "id": "seed-vocal-alchemy-open-rehearsal-2026-09-22",
  "title": "Vocal Alchemy open rehearsal",
  "group": "Vocal Alchemy",
  "type": "Open rehearsal",
  "date": "2026-09-22",
  "verified": "2026-09-12",
  "sourceName": "vocalalchemy.com",
  "time": "19:00",
  "endTime": "21:30",
  "venue": "Central Edmonton rehearsal hall (address given on request)",
  "description": "Second drop-in night of the fall for singers curious about the choir; the venue address is shared after you submit an interest form.",
  "link": "https://www.vocalalchemy.com/sing-with-us",
  "source": "https://www.vocalalchemy.com/sing-with-us"
 },
 {
  "id": "seed-sing-with-ekosingers-open-rehearsal-2026-09-22",
  "title": "Sing with EKOSingers! Open Rehearsal",
  "group": "EKOSingers",
  "type": "Open rehearsal",
  "date": "2026-09-22",
  "verified": "2026-09-12",
  "sourceName": "tockify.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "St. Luke's Anglican Church",
  "address": "8424 95 Avenue NW, Edmonton, AB",
  "description": "Last of the drop-in rehearsals where prospective members can try the choir's swing and pop repertoire before committing to a season.",
  "price": "Free",
  "link": "https://www.ekosingers.com/joinus",
  "source": "https://tockify.com/choiralberta/detail/1407/1788917400000"
 },
 {
  "id": "seed-the-splendours-of-the-tudor-era-byrd-2026-09-27",
  "title": "The Splendours of the Tudor Era: Byrd & Tallis",
  "group": "Schola Cantorum of St Joseph's Basilica",
  "type": "Concert",
  "date": "2026-09-27",
  "verified": "2026-09-12",
  "sourceName": "eventbrite.ca",
  "time": "15:00",
  "endTime": "16:15",
  "venue": "St. Joseph's Cathedral Basilica",
  "address": "10044 113 Street NW, Edmonton, AB",
  "description": "The basilica's Renaissance choir sings Tallis and Byrd, including the Lamentations of Jeremiah and a five-voice Mass, in a very resonant room.",
  "price": "Free",
  "link": "https://www.eventbrite.ca/e/the-splendours-of-the-tudor-era-byrd-tallis-tickets-1996034478858",
  "source": "https://www.eventbrite.ca/e/the-splendours-of-the-tudor-era-byrd-tallis-tickets-1996034478858"
 },
 {
  "id": "seed-evm-open-rehearsal-2026-09-28",
  "title": "EVM open rehearsal",
  "group": "Edmonton Vocal Minority",
  "type": "Open rehearsal",
  "date": "2026-09-28",
  "verified": "2026-09-12",
  "sourceName": "evmchoir.com",
  "time": "19:00",
  "endTime": "21:00",
  "venue": "Unitarian Church of Edmonton",
  "address": "10804 119 Street NW, Edmonton, AB",
  "description": "Final September drop-in night for singers thinking of joining the choir for its 2026-27 season.",
  "link": "https://evmchoir.com/join",
  "source": "https://evmchoir.com/join"
 },
 {
  "id": "seed-a-day-of-chilean-song-and-memory-2026-10-04",
  "title": "A Day of Chilean Song and Memory",
  "group": "Amigos de la Memoria of Edmonton",
  "type": "Concert",
  "date": "2026-10-04",
  "verified": "2026-09-12",
  "sourceName": "showpass.com",
  "time": "14:00",
  "endTime": "16:00",
  "venue": "Myer Horowitz Theatre",
  "address": "8900 114 Street NW, Edmonton, AB",
  "description": "Two Luis Advis cantatas built on sung narrative and Chilean folk rhythms are staged with dancers, telling stories of Violeta Parra and a 1907 massacre.",
  "price": "$38.69",
  "link": "https://www.showpass.com/a-day-of-chilean-song-and-memory/",
  "source": "https://www.showpass.com/a-day-of-chilean-song-and-memory/"
 },
 {
  "id": "seed-african-choir-drum-circle-fall-2026-2026-10-04",
  "title": "African Choir & Drum Circle: Fall 2026 Season",
  "group": "African Music Academy of Canada",
  "type": "Workshop or class",
  "date": "2026-10-04",
  "verified": "2026-09-12",
  "sourceName": "eventbrite.ca",
  "time": "18:30",
  "endDate": "2026-12-13",
  "venue": "Old Strathcona Performing Arts Centre",
  "address": "8426 Gateway Boulevard NW, Edmonton, AB",
  "description": "A weekly program pairing African-rooted group singing with hand drumming, open to complete beginners aged sixteen and up.",
  "price": "$300 full season, $150 members",
  "link": "https://www.eventbrite.ca/e/african-choir-drum-circle-fall-2026-season-tickets-1999118763035",
  "source": "https://www.eventbrite.ca/e/african-choir-drum-circle-fall-2026-season-tickets-1999118763035"
 },
 {
  "id": "seed-choral-evensong-2026-10-04",
  "title": "Choral Evensong",
  "group": "All Saints' Anglican Cathedral Choir",
  "type": "Other",
  "date": "2026-10-04",
  "verified": "2026-09-12",
  "sourceName": "allsaintscathedral.ca",
  "time": "19:00",
  "endTime": "20:00",
  "venue": "All Saints' Anglican Cathedral",
  "address": "10035 103 Street NW, Edmonton, AB",
  "description": "A sung evening prayer service in which the cathedral choir carries almost all the music; anyone may come and listen.",
  "price": "Free",
  "link": "https://allsaintscathedral.ca/events",
  "source": "https://allsaintscathedral.ca/events"
 },
 {
  "id": "seed-songs-of-the-harvest-moon-2026-10-16",
  "title": "Songs of the Harvest Moon",
  "group": "Pro Coro Canada",
  "type": "Concert",
  "date": "2026-10-16",
  "verified": "2026-09-12",
  "sourceName": "tickettailor.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "First Presbyterian Church",
  "address": "10025 105 St NW, Edmonton, AB",
  "description": "An autumn programme from Edmonton's professional chamber choir, built around harvest and moonlight imagery in choral repertoire.",
  "price": "$38 general, $10 student (plus tax)",
  "link": "https://www.tickettailor.com/events/procorocanada/2318145",
  "source": "https://www.tickettailor.com/events/procorocanada/"
 },
 {
  "id": "seed-every-voice-family-celebration-2026-10-18",
  "title": "Every Voice Family Celebration",
  "group": "Seeka Sings",
  "type": "Sing-along",
  "date": "2026-10-18",
  "verified": "2026-09-12",
  "sourceName": "eventbrite.ca",
  "time": "14:30",
  "endTime": "16:30",
  "venue": "Jamaica Association of Northern Alberta",
  "address": "10420 103 Avenue NW, Edmonton, AB",
  "description": "A family afternoon of songs and stories marking the release of a children's album and its companion sing-along picture book.",
  "price": "$10 individual, $30 family pass",
  "link": "https://www.eventbrite.ca/e/every-voice-family-celebration-tickets-1996456502141",
  "source": "https://www.eventbrite.ca/d/canada--edmonton/singing/"
 },
 {
  "id": "seed-malmo-plains-christmas-choir-2026-we-2026-10-19",
  "title": "Malmo Plains Christmas Choir 2026 - weekly rehearsals",
  "group": "Malmo Plains Christmas Choir",
  "type": "Workshop or class",
  "date": "2026-10-19",
  "verified": "2026-09-12",
  "sourceName": "eventbrite.ca",
  "time": "19:30",
  "endTime": "20:30",
  "endDate": "2026-12-06",
  "venue": "Holy Spirit Lutheran Church",
  "address": "11223 51 Ave NW, Edmonton, AB",
  "description": "Weekly Monday evening rehearsals of a neighbourhood Christmas choir, open to complete beginners as well as experienced singers, building toward a December concert.",
  "link": "https://www.eventbrite.ca/e/malmo-plains-christmas-choir-2026-tickets-1998469754834",
  "source": "https://www.eventbrite.ca/d/canada--edmonton/choir/"
 },
 {
  "id": "seed-gold-city-quartet-with-scotty-inman-2026-10-31",
  "title": "Gold City Quartet with Scotty Inman",
  "group": "Gold City",
  "type": "Concert",
  "date": "2026-10-31",
  "verified": "2026-09-12",
  "sourceName": "eventbrite.ca",
  "time": "15:00",
  "endTime": "17:30",
  "venue": "West End Christian Reformed Church",
  "address": "10015 149 Street NW, Edmonton, AB",
  "description": "A long-running American southern gospel vocal quartet performs an afternoon of four-part harmony interspersed with spoken testimony.",
  "link": "https://www.eventbrite.com/e/gold-city-quartet-with-scotty-inman-tickets-1998219939630",
  "source": "https://www.eventbrite.ca/d/canada--edmonton/singing/"
 },
 {
  "id": "seed-the-barber-of-seville-2026-11-05",
  "title": "The Barber of Seville",
  "group": "Edmonton Opera",
  "type": "Concert",
  "date": "2026-11-05",
  "verified": "2026-09-12",
  "sourceName": "edmontonopera.com",
  "time": "19:30",
  "venue": "Northern Alberta Jubilee Auditorium",
  "description": "Opera production, listed because the volunteer Edmonton Opera Chorus sings alongside the Edmonton Symphony Orchestra in Rossini's comedy.",
  "link": "https://tickets.edmontonopera.com/8650/8652",
  "source": "https://www.edmontonopera.com/barber-of-seville"
 },
 {
  "id": "seed-benedict-sheehan-s-ukrainian-war-req-2026-11-06",
  "title": "Benedict Sheehan's Ukrainian War Requiem - The National Tour",
  "group": "Axios Men's Ensemble",
  "type": "Concert",
  "date": "2026-11-06",
  "verified": "2026-09-12",
  "sourceName": "choiralberta.ca",
  "time": "19:00",
  "endTime": "21:00",
  "venue": "St. Basil's Ukrainian Catholic Church",
  "address": "7007 109 Street NW, Edmonton, AB",
  "description": "Edmonton's Juno-winning male vocal ensemble sings the requiem whose recording won them classical album of the year.",
  "link": "https://tockify.com/choiralberta/detail/1395/1794016800000",
  "source": "https://www.choiralberta.ca/calendar.html"
 },
 {
  "id": "seed-lest-we-forget-2026-11-07",
  "title": "Lest We Forget",
  "group": "Cosmopolitan Music Society - Monday Band and Chorus",
  "type": "Concert",
  "date": "2026-11-07",
  "verified": "2026-09-12",
  "sourceName": "cosmopolitanmusic.org",
  "time": "14:30",
  "venue": "Morinville Community Cultural Centre",
  "description": "The society's chorus shares a Remembrance-themed afternoon programme with one of its concert bands, north of the city in Morinville.",
  "link": "https://www.cosmopolitanmusic.org/upcoming-concerts-events",
  "source": "https://www.cosmopolitanmusic.org/upcoming-concerts-events"
 },
 {
  "id": "seed-the-barber-of-seville-2026-11-07",
  "title": "The Barber of Seville",
  "group": "Edmonton Opera",
  "type": "Concert",
  "date": "2026-11-07",
  "verified": "2026-09-12",
  "sourceName": "edmontonopera.com",
  "time": "19:30",
  "venue": "Northern Alberta Jubilee Auditorium",
  "description": "Second performance of Rossini's comedy; an opera production, included because the local Edmonton Opera Chorus is part of it.",
  "link": "https://tickets.edmontonopera.com/8650/8652",
  "source": "https://www.edmontonopera.com/barber-of-seville"
 },
 {
  "id": "seed-w-a-mozart-requiem-2026-11-08",
  "title": "W.A. Mozart | Requiem",
  "group": "Chorus Inspira",
  "type": "Concert",
  "date": "2026-11-08",
  "verified": "2026-09-12",
  "sourceName": "winspearcentre.com",
  "time": "15:00",
  "venue": "Francis Winspear Centre for Music",
  "address": "4 Sir Winston Churchill Square NW, Edmonton, AB",
  "description": "Edmonton's large symphonic choir performs Mozart's Requiem with the Edmonton Symphony Orchestra and four Canadian vocal soloists.",
  "price": "$45-$65 plus service charges",
  "link": "https://www.winspearcentre.com/tickets/events/other/2026/mozarts-requiem/",
  "source": "https://www.winspearcentre.com/tickets/events/other/2026/mozarts-requiem/"
 },
 {
  "id": "seed-124-street-light-up-festival-2026-11-14",
  "title": "124 Street Light Up Festival",
  "group": "Northern Harmony Chorus",
  "type": "Other",
  "date": "2026-11-14",
  "verified": "2026-09-12",
  "sourceName": "nhchorus.ca",
  "venue": "124 Street, Edmonton (exact spot to be announced)",
  "description": "The men's barbershop chorus sings outdoors at this west-end street festival; the organisers had not yet posted a set time.",
  "link": "https://nhchorus.ca/events/124st-light-up-festival/",
  "source": "https://nhchorus.ca/events-dir/"
 },
 {
  "id": "seed-rumbold-vocal-prize-masterclass-2026-11-16",
  "title": "Rumbold Vocal Prize Masterclass",
  "group": "Edmonton Opera",
  "type": "Workshop or class",
  "date": "2026-11-16",
  "verified": "2026-09-12",
  "sourceName": "edmontonopera.com",
  "venue": "Taylor College & Seminary",
  "description": "Finalists in Edmonton Opera's national singing competition are coached in public, so listeners hear the teaching as well as the voices.",
  "link": "https://www.edmontonopera.com/rumbold-vocal-prize-26",
  "source": "https://www.edmontonopera.com/"
 },
 {
  "id": "seed-rumbold-vocal-prize-grand-finale-2026-11-20",
  "title": "Rumbold Vocal Prize Grand Finale",
  "group": "Edmonton Opera",
  "type": "Concert",
  "date": "2026-11-20",
  "verified": "2026-09-12",
  "sourceName": "edmontonopera.com",
  "venue": "Myer Horowitz Theatre",
  "description": "Rising Canadian opera singers compete in a concert-format final for what Edmonton Opera bills as the country's top vocal award.",
  "link": "https://www.edmontonopera.com/rumbold-vocal-prize-26",
  "source": "https://www.edmontonopera.com/"
 },
 {
  "id": "seed-it-s-a-candy-cane-christmas-2026-11-28",
  "title": "It's a Candy-Cane Christmas",
  "group": "Northern Harmony Chorus",
  "type": "Concert",
  "date": "2026-11-28",
  "verified": "2026-09-12",
  "sourceName": "nhchorus.ca",
  "venue": "St. Andrew's United Church",
  "address": "9915 148 St NW, Edmonton, AB",
  "description": "The chorus's yearly holiday show of four-part barbershop harmony, moved this season to a larger west-end church.",
  "link": "https://nhchorus.ca/events/2026-christmas-show/",
  "source": "https://nhchorus.ca/events-dir/"
 },
 {
  "id": "seed-keys-to-the-heart-piano-human-voice-2026-11-29",
  "title": "Keys to the Heart... piano & human voice",
  "group": "Edmonton Metropolitan Chorus",
  "type": "Concert",
  "date": "2026-11-29",
  "verified": "2026-09-12",
  "sourceName": "edmetrochorus.ca",
  "time": "15:00",
  "endTime": "16:00",
  "venue": "First Presbyterian Church",
  "address": "10025 105 St NW, Edmonton, AB",
  "description": "The non-auditioned community chorus opens its 22nd season with an hour of repertoire pairing massed voices with piano.",
  "link": "https://edmetrochorus.ca/concert-season/",
  "source": "https://edmetrochorus.ca/wp-content/uploads/2026/09/EdMetro-Chorus-REH-PERF-Schedule-2026-2027-v2.pdf"
 },
 {
  "id": "seed-music-for-a-festive-season-2026-11-29",
  "title": "Music for a Festive Season",
  "group": "Alberta Baroque Ensemble with Coristi Chamber Choir",
  "type": "Concert",
  "date": "2026-11-29",
  "verified": "2026-09-12",
  "sourceName": "albertabaroque.com",
  "time": "15:00",
  "venue": "Robertson-Wesley United Church",
  "address": "10209 123 Street NW, Edmonton, AB",
  "description": "A chamber choir and three vocal soloists join the period-instrument ensemble for seasonal works by Handel, Vivaldi, Bach and Schiassi.",
  "price": "$35 adult, $15 student, free under 12",
  "link": "https://albertabaroque.com/",
  "source": "https://albertabaroque.com/"
 },
 {
  "id": "seed-christmas-at-city-hall-2026-12-06",
  "title": "Christmas at City Hall",
  "group": "EKOSingers",
  "type": "Concert",
  "date": "2026-12-06",
  "verified": "2026-09-12",
  "sourceName": "ekosingers.com",
  "time": "14:00",
  "venue": "Edmonton City Hall",
  "description": "Edmonton's pop and jazz choir sings a free-standing holiday set in the City Hall atrium on a December Sunday afternoon.",
  "link": "https://www.ekosingers.com/upcoming-events",
  "source": "https://www.ekosingers.com/upcoming-events"
 },
 {
  "id": "seed-malmo-plains-christmas-choir-2026-co-2026-12-07",
  "title": "Malmo Plains Christmas Choir 2026 concert",
  "group": "Malmo Plains Christmas Choir",
  "type": "Sing-along",
  "date": "2026-12-07",
  "verified": "2026-09-12",
  "sourceName": "eventbrite.ca",
  "time": "19:00",
  "endTime": "20:00",
  "venue": "Holy Spirit Lutheran Church",
  "address": "11223 51 Avenue NW, Edmonton, AB",
  "description": "The neighbourhood choir's end-of-term Christmas performance, which sets aside part of the evening for the audience to sing along.",
  "link": "https://www.eventbrite.ca/e/malmo-plains-christmas-choir-2026-tickets-1998469754834",
  "source": "https://www.eventbrite.ca/d/canada--edmonton/choir/"
 },
 {
  "id": "seed-handel-s-messiah-2026-12-11",
  "title": "Handel's Messiah",
  "group": "Edmonton Symphony Orchestra",
  "type": "Concert",
  "date": "2026-12-11",
  "verified": "2026-09-12",
  "sourceName": "winspearcentre.com",
  "time": "19:30",
  "venue": "Francis Winspear Centre for Music",
  "address": "4 Sir Winston Churchill Square NW, Edmonton, AB",
  "description": "The annual Messiah, with the chorus carrying the bulk of the work including the Hallelujah chorus, conducted by Jean-Marie Zeitouni.",
  "link": "https://www.winspearcentre.com/tickets/events/eso/2026/handels-messiah/",
  "source": "https://www.winspearcentre.com/tickets/events/eso/2026/handels-messiah/"
 },
 {
  "id": "seed-un-silent-night-an-epic-holiday-sing-2026-12-12",
  "title": "Un-Silent Night: An EPIC Holiday Sing-Along!",
  "group": "Choir! Choir! Choir!",
  "type": "Sing-along",
  "date": "2026-12-12",
  "verified": "2026-09-12",
  "sourceName": "ticketmaster.ca",
  "time": "19:00",
  "venue": "Midway Music Hall",
  "description": "Toronto's drop-in singing phenomenon hands out parts at the door and turns the whole room into a holiday choir for the night.",
  "link": "https://www.ticketmaster.ca/choir-choir-choir-unsilent-night-an-edmonton-alberta-12-12-2026/event/1100649E94417726",
  "source": "https://www.ticketmaster.ca/choir-choir-choir-tickets/artist/2083501"
 },
 {
  "id": "seed-handel-s-messiah-2026-12-12",
  "title": "Handel's Messiah",
  "group": "Edmonton Symphony Orchestra",
  "type": "Concert",
  "date": "2026-12-12",
  "verified": "2026-09-12",
  "sourceName": "winspearcentre.com",
  "time": "19:30",
  "venue": "Francis Winspear Centre for Music",
  "address": "4 Sir Winston Churchill Square NW, Edmonton, AB",
  "description": "Second performance of Handel's choral oratorio, a long-standing Edmonton holiday fixture, led by Jean-Marie Zeitouni.",
  "link": "https://www.winspearcentre.com/tickets/events/eso/2026/handels-messiah/",
  "source": "https://www.winspearcentre.com/tickets/events/eso/2026/handels-messiah/"
 },
 {
  "id": "seed-a-very-cosmo-christmas-sunday-matine-2026-12-13",
  "title": "A Very Cosmo Christmas Sunday Matinee",
  "group": "Cosmopolitan Music Society - Cosmopolitones and Chorus",
  "type": "Concert",
  "date": "2026-12-13",
  "verified": "2026-09-12",
  "sourceName": "cosmopolitanmusic.org",
  "time": "14:30",
  "venue": "Old Strathcona Performing Arts Centre",
  "address": "8426 Gateway Boulevard NW, Edmonton, AB",
  "description": "An all-vocal holiday matinee featuring both of the society's singing groups, the Cosmopolitones and the larger Chorus.",
  "link": "https://www.cosmopolitanmusic.org/upcoming-concerts-events",
  "source": "https://www.cosmopolitanmusic.org/upcoming-concerts-events"
 },
 {
  "id": "seed-a-christmas-carol-2026-12-13",
  "title": "A Christmas Carol",
  "group": "Pro Coro Canada",
  "type": "Concert",
  "date": "2026-12-13",
  "verified": "2026-09-12",
  "sourceName": "tickettailor.com",
  "time": "15:00",
  "endTime": "17:00",
  "venue": "First Presbyterian Church",
  "address": "10025 105 St NW, Edmonton, AB",
  "description": "A Sunday afternoon holiday concert from the professional chamber choir, taking Dickens' Christmas story as its starting point.",
  "price": "$38 general, $10 student (plus tax)",
  "link": "https://www.tickettailor.com/events/procorocanada/2318146",
  "source": "https://www.tickettailor.com/events/procorocanada/"
 },
 {
  "id": "seed-a-chorus-inspira-christmas-2026-12-18",
  "title": "A Chorus Inspira Christmas!",
  "group": "Chorus Inspira",
  "type": "Concert",
  "date": "2026-12-18",
  "verified": "2026-09-12",
  "sourceName": "stalbert.ca",
  "time": "19:30",
  "endTime": "21:50",
  "venue": "Arden Theatre, St. Albert",
  "address": "5 St. Anne Street, St. Albert, AB",
  "description": "The hundred-voice symphonic choir takes carols and Messiah excerpts to St. Albert, accompanied by grand piano rather than orchestra.",
  "price": "$30.00-$47.80 including GST and fees",
  "link": "https://stalbert.ca/exp/arden/events/a-chorus-inspira-christmas/",
  "source": "https://stalbert.ca/exp/arden/events/a-chorus-inspira-christmas/"
 },
 {
  "id": "seed-a-chorus-inspira-christmas-2026-12-19",
  "title": "A Chorus Inspira Christmas!",
  "group": "Chorus Inspira",
  "type": "Concert",
  "date": "2026-12-19",
  "verified": "2026-09-12",
  "sourceName": "chorusinspira.ca",
  "time": "19:30",
  "venue": "Horizon Stage, Spruce Grove",
  "description": "The same festive carol and Handel programme travels west to Spruce Grove for a second night with piano accompaniment.",
  "price": "$40 regular, $25 student",
  "link": "https://chorusinspira.ca/home/2026-2027-season/a-chorus-inspira-christmas/",
  "source": "https://chorusinspira.ca/home/2026-2027-season/a-chorus-inspira-christmas/"
 },
 {
  "id": "seed-the-little-match-girl-passion-2026-12-20",
  "title": "The Little Match Girl Passion",
  "group": "Pro Coro Canada",
  "type": "Concert",
  "date": "2026-12-20",
  "verified": "2026-09-12",
  "sourceName": "tickettailor.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "All Saints' Anglican Cathedral",
  "address": "10035 103 Street NW, Edmonton, AB",
  "description": "Pro Coro performs David Lang's spare, haunting retelling of the Andersen fairy tale in the cathedral's resonant acoustic.",
  "price": "$38 general, $10 student (plus tax)",
  "link": "https://www.tickettailor.com/events/procorocanada/2318156",
  "source": "https://www.tickettailor.com/events/procorocanada/"
 },
 {
  "id": "seed-new-year-s-eve-with-pro-coro-canada-2026-12-31",
  "title": "New Year's Eve with Pro Coro Canada",
  "group": "Pro Coro Canada",
  "type": "Concert",
  "date": "2026-12-31",
  "verified": "2026-09-12",
  "sourceName": "tickettailor.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "ArtsHub Ortona",
  "address": "9722 102 Street NW, Edmonton, AB",
  "description": "Ring out the year with Edmonton's professional chamber choir in an informal New Year's Eve programme at the Ortona arts hub.",
  "link": "https://www.tickettailor.com/events/procorocanada/2318157",
  "source": "https://www.tickettailor.com/events/procorocanada/"
 },
 {
  "id": "seed-edmetro-chorus-rehearsal-new-members-2027-01-11",
  "title": "EdMetro Chorus rehearsal - new members welcome",
  "group": "Edmonton Metropolitan Chorus",
  "type": "Open rehearsal",
  "date": "2027-01-11",
  "verified": "2026-09-12",
  "sourceName": "edmetrochorus.ca",
  "time": "19:00",
  "endTime": "21:00",
  "venue": "Strathearn United Church",
  "address": "8510 95 Ave NW, Edmonton, AB",
  "description": "The chorus reopens to new singers in January, letting people join partway through the season for the winter programme.",
  "link": "https://edmetrochorus.ca/how-to-join/",
  "source": "https://edmetrochorus.ca/wp-content/uploads/2026/09/EdMetro-Chorus-REH-PERF-Schedule-2026-2027-v2.pdf"
 },
 {
  "id": "seed-rejoice-alberta-season-ix-christian-2027-01-15",
  "title": "Rejoice Alberta Season IX - Christian Singing Competition Auditions",
  "group": "Rejoice Alberta",
  "type": "Auditions",
  "date": "2027-01-15",
  "verified": "2026-09-12",
  "sourceName": "eventbrite.ca",
  "time": "16:00",
  "endTime": "20:00",
  "venue": "6005 Gateway Boulevard NW",
  "address": "6005 Gateway Boulevard NW, Edmonton, AB",
  "description": "Solo singers, worship leaders and vocal groups audition in person or by video for a competition offering cash and a music video.",
  "price": "$100 application fee",
  "link": "https://www.eventbrite.ca/e/rejoice-alberta-season-ix-christian-singing-competition-auditions-tickets-2000213246665",
  "source": "https://www.eventbrite.ca/d/canada--edmonton/singing/"
 },
 {
  "id": "seed-missae-x-2027-01-30",
  "title": "Missae X",
  "group": "Pro Coro Canada",
  "type": "Concert",
  "date": "2027-01-30",
  "verified": "2026-09-12",
  "sourceName": "tickettailor.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "First Presbyterian Church",
  "address": "10025 105 St NW, Edmonton, AB",
  "description": "The tenth instalment of Pro Coro's long-running series exploring settings of the Mass across different centuries and styles.",
  "price": "$38 general, $10 student (plus tax)",
  "link": "https://www.tickettailor.com/events/procorocanada/2318147",
  "source": "https://www.tickettailor.com/events/procorocanada/"
 },
 {
  "id": "seed-the-magic-flute-2027-02-04",
  "title": "The Magic Flute",
  "group": "Edmonton Opera",
  "type": "Concert",
  "date": "2027-02-04",
  "verified": "2026-09-12",
  "sourceName": "edmontonopera.com",
  "time": "19:30",
  "venue": "Northern Alberta Jubilee Auditorium",
  "description": "Opera production, flagged here because the community-drawn Edmonton Opera Chorus features throughout Mozart's fairy-tale score.",
  "link": "https://tickets.edmontonopera.com/8655/8659",
  "source": "https://www.edmontonopera.com/the-magic-flute"
 },
 {
  "id": "seed-the-magic-flute-2027-02-06",
  "title": "The Magic Flute",
  "group": "Edmonton Opera",
  "type": "Concert",
  "date": "2027-02-06",
  "verified": "2026-09-12",
  "sourceName": "edmontonopera.com",
  "time": "19:30",
  "venue": "Northern Alberta Jubilee Auditorium",
  "description": "Closing night of Mozart's Magic Flute; an opera, included because the Edmonton Opera Chorus sings a central role.",
  "link": "https://tickets.edmontonopera.com/8655/8659",
  "source": "https://www.edmontonopera.com/the-magic-flute"
 },
 {
  "id": "seed-canadian-connections-x-featuring-the-2027-02-26",
  "title": "Canadian Connections X, featuring the Vancouver Chamber Choir",
  "group": "Pro Coro Canada",
  "type": "Concert",
  "date": "2027-02-26",
  "verified": "2026-09-12",
  "sourceName": "tickettailor.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "McDougall United Church",
  "address": "10086 MacDonald Drive NW, Edmonton, AB",
  "description": "Two of Canada's leading professional choirs share a stage for an evening of Canadian choral writing, old and newly commissioned.",
  "price": "$38 general, $10 student (plus tax)",
  "link": "https://www.tickettailor.com/events/procorocanada/2318148",
  "source": "https://www.tickettailor.com/events/procorocanada/"
 },
 {
  "id": "seed-jbb-and-cosmopolitones-concert-and-p-2027-03-05",
  "title": "JBB and Cosmopolitones concert and party",
  "group": "Cosmopolitan Music Society",
  "type": "Concert",
  "date": "2027-03-05",
  "verified": "2026-09-12",
  "sourceName": "cosmopolitanmusic.org",
  "time": "19:30",
  "venue": "Old Strathcona Performing Arts Centre",
  "address": "8426 Gateway Boulevard NW, Edmonton, AB",
  "description": "The Cosmopolitones vocal group fronts the society's jazz big band for an evening concert that turns into a dance party.",
  "link": "https://www.cosmopolitanmusic.org/upcoming-concerts-events",
  "source": "https://www.cosmopolitanmusic.org/upcoming-concerts-events"
 },
 {
  "id": "seed-unaccompanied-unlimited-2027-03-07",
  "title": "Unaccompanied... Unlimited",
  "group": "Edmonton Metropolitan Chorus",
  "type": "Concert",
  "date": "2027-03-07",
  "verified": "2026-09-12",
  "sourceName": "edmetrochorus.ca",
  "time": "15:00",
  "endTime": "16:00",
  "venue": "First Presbyterian Church",
  "address": "10025 105 St NW, Edmonton, AB",
  "description": "An all-a-cappella hour from the community chorus, conducted by Graham Fast, with no instruments behind the voices.",
  "link": "https://edmetrochorus.ca/concert-season/",
  "source": "https://edmetrochorus.ca/wp-content/uploads/2026/09/EdMetro-Chorus-REH-PERF-Schedule-2026-2027-v2.pdf"
 },
 {
  "id": "seed-glorious-chorus-verdi-s-sacred-piece-2027-03-12",
  "title": "Glorious Chorus: Verdi's Sacred Pieces",
  "group": "Chorus Inspira",
  "type": "Concert",
  "date": "2027-03-12",
  "verified": "2026-09-12",
  "sourceName": "winspearcentre.com",
  "time": "19:30",
  "venue": "Francis Winspear Centre for Music",
  "address": "4 Sir Winston Churchill Square NW, Edmonton, AB",
  "description": "Chorus Inspira and the Edmonton Symphony Orchestra take on Verdi's sacred choral writing, music built for a very large choir.",
  "link": "https://www.winspearcentre.com/tickets/events/eso/2027/glorious-chorus-verdis-sacred-pieces/",
  "source": "https://www.winspearcentre.com/tickets/events/eso/2027/glorious-chorus-verdis-sacred-pieces/"
 },
 {
  "id": "seed-glorious-chorus-verdi-s-sacred-piece-2027-03-13",
  "title": "Glorious Chorus: Verdi's Sacred Pieces",
  "group": "Chorus Inspira",
  "type": "Concert",
  "date": "2027-03-13",
  "verified": "2026-09-12",
  "sourceName": "winspearcentre.com",
  "time": "19:30",
  "venue": "Francis Winspear Centre for Music",
  "address": "4 Sir Winston Churchill Square NW, Edmonton, AB",
  "description": "Repeat performance of Verdi's sacred choral pieces with Chorus Inspira joining the Edmonton Symphony Orchestra.",
  "link": "https://www.winspearcentre.com/tickets/events/eso/2027/glorious-chorus-verdis-sacred-pieces/",
  "source": "https://www.winspearcentre.com/tickets/events/eso/2027/glorious-chorus-verdis-sacred-pieces/"
 },
 {
  "id": "seed-a-cappella-ensemble-and-guitar-band-2027-03-21",
  "title": "A Cappella Ensemble and Guitar Band Concert",
  "group": "MacEwan University A Cappella Ensemble",
  "type": "Concert",
  "date": "2027-03-21",
  "verified": "2026-09-12",
  "sourceName": "macewan.ca",
  "time": "14:00",
  "endTime": "17:00",
  "venue": "Betty Andrews Recital Hall, Allard Hall, MacEwan University",
  "address": "11110 104 Avenue NW, Edmonton, AB",
  "description": "MacEwan's student a cappella group shares an afternoon programme with the guitar band, mixing close vocal harmony and instrumental arrangements.",
  "link": "https://www.macewan.ca/academics/academic-departments/music/music-season/",
  "source": "https://www.macewan.ca/academics/academic-departments/music/music-season/"
 },
 {
  "id": "seed-spring-sundays-monday-band-and-choru-2027-03-21",
  "title": "Spring Sundays: Monday Band and Chorus",
  "group": "Cosmopolitan Music Society",
  "type": "Concert",
  "date": "2027-03-21",
  "verified": "2026-09-12",
  "sourceName": "cosmopolitanmusic.org",
  "time": "14:30",
  "venue": "Old Strathcona Performing Arts Centre",
  "address": "8426 Gateway Boulevard NW, Edmonton, AB",
  "description": "The community chorus returns to the Old Strathcona hall for a spring afternoon shared with one of the society's concert bands.",
  "link": "https://www.cosmopolitanmusic.org/upcoming-concerts-events",
  "source": "https://www.cosmopolitanmusic.org/upcoming-concerts-events"
 },
 {
  "id": "seed-edmetro-chorus-rehearsal-new-members-2027-03-22",
  "title": "EdMetro Chorus rehearsal - new members welcome",
  "group": "Edmonton Metropolitan Chorus",
  "type": "Open rehearsal",
  "date": "2027-03-22",
  "verified": "2026-09-12",
  "sourceName": "edmetrochorus.ca",
  "time": "19:00",
  "endTime": "21:00",
  "venue": "Strathearn United Church",
  "address": "8510 95 Ave NW, Edmonton, AB",
  "description": "A third intake point in the choral year, as the chorus begins preparing music for its late-May season finale.",
  "link": "https://edmetrochorus.ca/how-to-join/",
  "source": "https://edmetrochorus.ca/wp-content/uploads/2026/09/EdMetro-Chorus-REH-PERF-Schedule-2026-2027-v2.pdf"
 },
 {
  "id": "seed-good-friday-with-pro-coro-canada-fea-2027-03-26",
  "title": "Good Friday with Pro Coro Canada, featuring Chorale Saint-Jean",
  "group": "Pro Coro Canada",
  "type": "Concert",
  "date": "2027-03-26",
  "verified": "2026-09-12",
  "sourceName": "tickettailor.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "Winspear Centre",
  "description": "Pro Coro joins the francophone Chorale Saint-Jean for a Good Friday programme of reflective sacred choral music.",
  "link": "https://www.tickettailor.com/events/procorocanada/2318149",
  "source": "https://www.tickettailor.com/events/procorocanada/"
 },
 {
  "id": "seed-the-city-full-of-people-featuring-ca-2027-04-17",
  "title": "The City, Full of People, featuring Cameron Crozman, cello",
  "group": "Pro Coro Canada",
  "type": "Concert",
  "date": "2027-04-17",
  "verified": "2026-09-12",
  "sourceName": "tickettailor.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "All Saints' Anglican Cathedral",
  "address": "10035 103 Street NW, Edmonton, AB",
  "description": "Choral music about urban life and crowds, with cellist Cameron Crozman weaving solo lines between the voices.",
  "price": "$38 general, $10 student (plus tax)",
  "link": "https://www.tickettailor.com/events/procorocanada/2318150",
  "source": "https://www.tickettailor.com/events/procorocanada/"
 },
 {
  "id": "seed-j-s-bach-st-matthew-passion-2027-05-16",
  "title": "J.S. Bach | St. Matthew Passion",
  "group": "Chorus Inspira",
  "type": "Concert",
  "date": "2027-05-16",
  "verified": "2026-09-12",
  "sourceName": "winspearcentre.com",
  "time": "15:00",
  "venue": "Francis Winspear Centre for Music",
  "address": "4 Sir Winston Churchill Square NW, Edmonton, AB",
  "description": "Chorus Inspira closes its season with Bach's monumental Passion, accompanied by the period-instrument Rosa Barocca orchestra.",
  "price": "$45-$65 plus service charges",
  "link": "https://www.winspearcentre.com/tickets/events/other/2027/j-s-bach-st-matthew-passion/",
  "source": "https://www.winspearcentre.com/tickets/events/other/2027/j-s-bach-st-matthew-passion/"
 },
 {
  "id": "seed-alleyway-psalms-2027-05-28",
  "title": "Alleyway Psalms",
  "group": "Pro Coro Canada",
  "type": "Concert",
  "date": "2027-05-28",
  "verified": "2026-09-12",
  "sourceName": "tickettailor.com",
  "time": "19:30",
  "endTime": "21:30",
  "venue": "To be announced",
  "description": "Pro Coro closes its season with a programme of psalm settings; the venue had not been confirmed at the time of listing.",
  "price": "$38 general, $10 student (plus tax)",
  "link": "https://www.tickettailor.com/events/procorocanada/2318151",
  "source": "https://www.tickettailor.com/events/procorocanada/"
 },
 {
  "id": "seed-ekosingers-spring-concert-2027-05-29",
  "title": "EKOSingers Spring Concert",
  "group": "EKOSingers",
  "type": "Concert",
  "date": "2027-05-29",
  "verified": "2026-09-12",
  "sourceName": "ekosingers.com",
  "time": "19:30",
  "venue": "Westbury Theatre, ATB Financial Arts Barns",
  "description": "The pop, rock, jazz and folk choir closes its season with a staged evening show in the Arts Barns' largest theatre.",
  "link": "https://www.ekosingers.com/upcoming-events",
  "source": "https://www.ekosingers.com/upcoming-events"
 },
 {
  "id": "seed-ekosingers-spring-concert-2027-05-30",
  "title": "EKOSingers Spring Concert",
  "group": "EKOSingers",
  "type": "Concert",
  "date": "2027-05-30",
  "verified": "2026-09-12",
  "sourceName": "ekosingers.com",
  "time": "14:30",
  "venue": "Westbury Theatre, ATB Financial Arts Barns",
  "description": "Matinee repeat of the choir's season finale, drawing on rock, jazz, folk and pop arrangements for mixed voices.",
  "link": "https://www.ekosingers.com/upcoming-events",
  "source": "https://www.ekosingers.com/upcoming-events"
 },
 {
  "id": "seed-from-truth-comes-hope-2027-05-30",
  "title": "From Truth... Comes Hope",
  "group": "Edmonton Metropolitan Chorus",
  "type": "Concert",
  "date": "2027-05-30",
  "verified": "2026-09-12",
  "sourceName": "edmetrochorus.ca",
  "time": "15:00",
  "endTime": "16:00",
  "venue": "First Presbyterian Church",
  "address": "10025 105 St NW, Edmonton, AB",
  "description": "The chorus closes its season with an hour-long programme on themes of truth and hope, conducted by David Garber.",
  "link": "https://edmetrochorus.ca/concert-season/",
  "source": "https://edmetrochorus.ca/wp-content/uploads/2026/09/EdMetro-Chorus-REH-PERF-Schedule-2026-2027-v2.pdf"
 }
];
